{% set name = "pinout" %}
{% set version = "0.0.20" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pinout-{{ version }}.tar.gz
  sha256: 1859c8a0297542a236d9f92b55459226bb8d702c4ae43d9aad3e9a090d25ed17

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - jinja2
    - pillow
    - python >={{ python_min }}

test:
  imports:
    - pinout
    - pinout.components
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/j0ono0/pinout
  summary: Generate graphical pinout references for electronic hardware.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
