{% set name = "pinout" %}
{% set version = "0.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pinout-{{ version }}.tar.gz
  sha256: 4cbe84932e6b83879c5b1a0bc1fd490a883c71a7db5d364e1f47f032dd3afad0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - jinja2
    - pillow
    - python >={{ python_min }}

test:
  imports:
    - pinout
    - pinout.components
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/j0ono0/pinout
  summary: Generate graphical pinout references for electronic hardware.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
